import type {DailyCounts, DailyPost, DailySnapshot} from './CustomerDailyReport.types';
export const monthlyFields: readonly ['monitor', 'sdb', 'positive', 'neutral', 'cold', 'comment', 'negativeProcess', 'negativeOther'];
export type MonthlyField = typeof monthlyFields[number];
export type MonthlyDraft = Record<string, Partial<Record<MonthlyField, string>>>;
export const monthlyLabels: Record<MonthlyField, string>;
export function isMonthlySummary(snapshot: DailySnapshot): boolean;
export function isHandlingSummary(snapshot: DailySnapshot): boolean;
export function visibleMonthlyRows(rows: NonNullable<DailySnapshot['summary']['rows']>, includeHandledNonWorkingDays?: boolean): NonNullable<DailySnapshot['summary']['rows']>;
export function monthlyDraftFromRows(rows: NonNullable<DailySnapshot['summary']['rows']>, includeHandledNonWorkingDays?: boolean): MonthlyDraft;
export function parseMonthlyDraft(rows: NonNullable<DailySnapshot['summary']['rows']>, draft: MonthlyDraft, includeHandledNonWorkingDays?: boolean): {rows: Record<string, Record<MonthlyField, number>>};
export function sumMonthlyRows(rows: NonNullable<DailySnapshot['summary']['rows']>, draft: MonthlyDraft | null, includeHandledNonWorkingDays?: boolean): Pick<DailyCounts, MonthlyField>;
export function dailyPostStatusLabel(post: DailyPost): string;
