export const DOUYIN_DOM_PROFILE = Object.freeze({
  platform: "douyin",
  noteDetail: Object.freeze({
    ready: Object.freeze({
      anyOf: Object.freeze([
        '[data-e2e-aweme-id]',
        '[data-e2e="video-desc"]',
        '[data-e2e="feed-video-nickname"]',
        '[data-e2e="video-player-digg"]',
        '[data-e2e="detail-video-publish-time"]',
        "video",
      ]),
      minimumCount: 1,
    }),
    rootSelectors: Object.freeze([
      '[data-e2e-aweme-id]',
      'main [data-e2e="video-info"]',
      ".video-info-detail",
      "main article",
      "article",
      "main",
    ]),
    rootSignals: Object.freeze([
      '[data-e2e-aweme-id]',
      '[data-e2e="video-desc"]',
      '[data-e2e="feed-video-nickname"]',
      '[data-e2e="video-player-digg"]',
      '[data-e2e="feed-comment-icon"]',
      '[data-e2e="video-player-collect"]',
      '[data-e2e="video-player-share"]',
      '[data-e2e="detail-video-publish-time"]',
      '[data-e2e="video-avatar"][href*="/user/"]',
      "video",
    ]),
    rootValidationSelectors: Object.freeze([
      '[data-e2e="video-desc"]',
      '[data-e2e="feed-video-nickname"]',
      '[data-e2e="video-player-digg"]',
      "video",
    ]),
    fields: Object.freeze({
      noteId: Object.freeze([
        '[data-e2e-aweme-id]',
        'a[href*="/video/"]',
        'a[href*="/note/"]',
        "video",
      ]),
      title: Object.freeze([
        '[data-e2e="video-desc"]',
        ".video-info-detail .title",
        "h1.idrZUbq7",
        ".tYvuOjO8 h1",
        "h1",
      ]),
      authorName: Object.freeze([
        ".author-card-name",
        '[data-e2e="user-info"] h1',
        '[data-e2e="feed-video-nickname"]',
        ".video-info-detail .account-name-text",
        ".video-info-detail .account-name",
        ".OMAnlCHg .q5XQ42ql",
        'a[href*="/user/"]',
      ]),
      authorLink: Object.freeze([
        '.author-card a[href*="/user/"]',
        '.author-card-user-info a[href*="/user/"]',
        '[data-e2e="video-avatar"][href*="/user/"]',
        ".video-info-detail a[href*=\"/user/\"]",
        ".OMAnlCHg a[href*=\"/user/\"]",
        'a[href*="/user/"]',
      ]),
      publishTime: Object.freeze([
        '[data-e2e="detail-video-publish-time"]',
        ".video-info-detail .video-create-time .time",
        ".MsN3XzkF",
      ]),
      tags: Object.freeze([
        'a[href*="/search/"] span',
        'a[href*="/search/"]',
      ]),
      interactions: Object.freeze({
        likes: Object.freeze([
          '[data-e2e="video-player-digg"]',
          '[data-e2e="like-icon"]',
          '[data-e2e="feed-like-icon"]',
          ".fN2jqmuV .fcEX2ARL:nth-child(1)",
        ]),
        comments: Object.freeze([
          '[data-e2e="feed-comment-icon"]',
          '[data-e2e="comment-icon"]',
          ".DG40dqtZ",
          ".fN2jqmuV .fcEX2ARL:nth-child(2)",
        ]),
        collects: Object.freeze([
          '[data-e2e="video-player-collect"]',
          '[data-e2e="collect-icon"]',
          '[data-e2e="feed-collect-icon"]',
          ".fN2jqmuV .fcEX2ARL:nth-child(3)",
        ]),
        shares: Object.freeze([
          '[data-e2e="video-player-share"]',
          '[data-e2e="feed-share-icon"]',
          '[data-e2e="share-icon"]',
          ".fN2jqmuV .fcEX2ARL:nth-child(4)",
        ]),
      }),
      video: Object.freeze(["video"]),
      videoSources: Object.freeze(["source[src]"]),
      images: Object.freeze([
        '.swiper-slide-active img[src*="douyinpic.com"]',
        '.swiper-slide-active img[src*="byteimg.com"]',
        '[class*="swiper"] img[src*="douyinpic.com"]',
        '[class*="swiper"] img[src*="byteimg.com"]',
        '[data-e2e="video-info"] img[src]',
        "main img[src]",
        "article img[src]",
        'img[src*="douyinpic.com"]',
      ]),
      coverImage: Object.freeze([
        "video[poster]",
        'meta[property="og:image"]',
      ]),
    }),
  }),
  bloggerProfile: Object.freeze({
    ready: Object.freeze({
      anyOf: Object.freeze([
        '[data-e2e="user-info"]',
        '[data-e2e="user-post-list"]',
        '[data-e2e="user-info-fans"]',
        '[data-e2e="scroll-list"]',
      ]),
      minimumCount: 2,
    }),
    rootSelectors: Object.freeze([
      '[data-e2e="user-info"]',
      '[data-e2e="user-detail"]',
      "main",
    ]),
    rootSignals: Object.freeze([
      '[data-e2e="user-info"]',
      '[data-e2e="user-info-follow"]',
      '[data-e2e="user-info-fans"]',
      '[data-e2e="user-info-like"]',
      '[data-e2e="user-work-tab"]',
      '[data-e2e="user-post-list"]',
      '[data-e2e="scroll-list"]',
    ]),
    rootValidationSelectors: Object.freeze([
      '[data-e2e="user-info-fans"]',
      '[data-e2e="user-info-like"]',
      '[data-e2e="user-post-list"]',
    ]),
    fields: Object.freeze({
      bloggerLink: Object.freeze(['a[href*="/user/"]']),
      name: Object.freeze([
        ".D0hUQ1",
        '[data-e2e="user-info"] h1',
        '[data-e2e="feed-video-nickname"]',
        "h1",
      ]),
      avatar: Object.freeze([
        '[data-e2e="user-detail"] img[alt$="头像"]',
        '[data-e2e="user-detail"] > div > div:first-child img',
        ".yzJGz3HB img",
        '[data-e2e="live-avatar"] img',
        'img[src*="aweme-avatar"]',
      ]),
      description: Object.freeze([
        '[data-e2e="user-info"] > p + div > div > span',
        '[data-e2e="user-info"] > p + div > div',
        '[data-e2e="user-info"] > p + div',
        '[data-e2e="user-info"] > div:last-child > div > span',
        '[data-e2e="user-info"] > div:last-child > div',
        '[data-e2e="user-info"] > div:last-child',
        ".JMYmWBA1",
        '[data-e2e="user-desc"]',
        '[class*="user-desc"]',
      ]),
      followingCount: Object.freeze([
        '[data-e2e="user-info-follow"] .C1cxu0Vq',
        '[data-e2e="user-info-follow"] [class*="count"]',
      ]),
      followersCount: Object.freeze([
        '[data-e2e="user-info-fans"] .C1cxu0Vq',
        '[data-e2e="user-info-fans"] [class*="count"]',
      ]),
      likedAndCollectedCount: Object.freeze([
        '[data-e2e="user-info-like"] .C1cxu0Vq',
        '[data-e2e="user-info-like"] [class*="count"]',
      ]),
      accountType: Object.freeze([
        '[data-e2e="badge-role-name"]',
      ]),
    }),
    notesList: Object.freeze({
      rootSelectors: Object.freeze([
        '[data-e2e="user-post-list"]',
        '[data-e2e="scroll-list"]',
        ".scroll-list",
        "main",
      ]),
      cardSelectors: Object.freeze([
        '[data-e2e="user-post-list"] a[href^="/video/"]',
        '[data-e2e="user-post-list"] a[href^="/note/"]',
        '[data-e2e="scroll-list"] a[href^="/video/"]',
        '[data-e2e="scroll-list"] a[href^="/note/"]',
      ]),
      fields: Object.freeze({
        title: Object.freeze([
          ".EtttsrEw",
          ".eJFBAbdI",
          '[class*="title"]',
          "p",
          "img[alt]",
        ]),
        coverImage: Object.freeze([
          'img[src*="douyinpic.com"]',
          "img[src]",
        ]),
        likes: Object.freeze([
          ".author-card-user-video-like",
          ".author-card-user-video-like .BgCg_ebQ",
          '[class*="user-video-like"]',
          '[class*="video-like"]',
          '[class*="video-like"] span',
          '[class*="like"]',
          '[class*="like"] span',
        ]),
      }),
    }),
  }),
  searchResults: Object.freeze({
    ready: Object.freeze({
      anyOf: Object.freeze([
        '[data-e2e="searchbar-input"]',
        '#search-result-container',
        '#waterFallScrollContainer',
        '.search-result-card',
        '[id^="waterfall_item_"]',
      ]),
      minimumCount: 2,
    }),
    rootSelectors: Object.freeze([
      "#search-result-container",
      "#search-content-area",
      "#waterFallScrollContainer",
      '[data-e2e="scroll-list"]',
      ".scroll-list",
      "main",
    ]),
    rootSignals: Object.freeze([
      '[data-e2e="searchbar-input"]',
      '[data-e2e="searchbar-button"]',
      '#search-result-container',
      '#waterFallScrollContainer',
      '.search-result-card',
      '[id^="waterfall_item_"]',
    ]),
    rootValidationSelectors: Object.freeze([
      '#search-result-container',
      '#waterFallScrollContainer',
      '.search-result-card',
      '[id^="waterfall_item_"]',
    ]),
    fields: Object.freeze({
      searchInput: Object.freeze([
        '[data-e2e="searchbar-input"]',
        'input[type="search"]',
        'input[placeholder*="搜索"]',
      ]),
      suggestionDropdown: Object.freeze([
        '[data-e2e="searchbar-popup"]',
        '.search-suggest-popup',
        '[class*="suggestPopup"]',
        '[class*="suggest-popup"]',
        '[class*="SearchSuggest"]',
        '[class*="search-suggest"]',
      ]),
      suggestionItem: Object.freeze([
        '[data-e2e="searchbar-popup"] li',
        '.search-suggest-popup li',
        '[class*="suggestPopup"] li',
        '[class*="suggest-popup"] li',
        '[class*="SearchSuggest"] li',
        '[class*="search-suggest"] li',
        '[data-e2e="searchbar-popup"] [class*="item"]',
      ]),
      activeTab: Object.freeze([
        '#search-toolbar-container [data-key].XhvZyP3Y',
        '#search-toolbar-container [data-key][class*="XhvZyP3Y"]',
        '#search-toolbar-container [data-key][aria-selected="true"]',
      ]),
    }),
    cards: Object.freeze({
      cardSelectors: Object.freeze([
        '#search-result-container .search-result-card',
        '#waterFallScrollContainer .search-result-card',
        '#search-result-container [id^="waterfall_item_"]',
        '#waterFallScrollContainer [id^="waterfall_item_"]',
        '[data-e2e="scroll-list"] a[href*="/video/"]',
        '[data-e2e="scroll-list"] a[href*="/note/"]',
        '#search-result-container a[href*="/video/"]',
        '#search-result-container a[href*="/note/"]',
      ]),
      fields: Object.freeze({
        title: Object.freeze([
          '.search-result-card .BjLsdJMi',
          '.search-result-card .K4Ja9W9H',
          '.search-result-card [class*="desc"]',
          '.search-result-card [class*="title"]',
          '.search-result-card p',
        ]),
        coverImage: Object.freeze([
          '.search-result-card img[src*="douyinpic.com"]',
          '.search-result-card [style*="background-image"]',
          'img[src*="douyinpic.com"]',
          "img[src]",
        ]),
        author: Object.freeze([
          '.search-result-card .WldPmwm5',
          '.search-result-card .RY_wFBXl',
          '.search-result-card [class*="author"]',
          '.search-result-card [class*="nickname"]',
          '.search-result-card a[href*="/user/"]',
        ]),
        likes: Object.freeze([
          '.search-result-card .pMq55q1M',
          '.search-result-card .pMq55q1M span',
          '.search-result-card .AulOiP53',
          '.search-result-card [class*="like"]',
          '.search-result-card [class*="digg"]',
        ]),
        publishDate: Object.freeze([
          '.search-result-card .dO8W7uoF',
        ]),
        duration: Object.freeze([
          '.search-result-card .FnM1bbIQ',
        ]),
      }),
    }),
  }),
});
